# Generated by Django 5.1.3 on 2025-04-19 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='city',
        ),
        migrations.RemoveField(
            model_name='university',
            name='country',
        ),
        migrations.RemoveField(
            model_name='university',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='university',
            name='website',
        ),
    ]
