# Generated by Django 4.2.7 on 2025-06-26 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_notebook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notebook',
        ),
    ]
