# Generated by Django 5.1.3 on 2025-06-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_firebase_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='place',
            field=models.CharField(blank=True, help_text='User location/place for location-based features', max_length=255, null=True),
        ),
    ]
