# Generated by Django 5.1.3 on 2025-06-29 20:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_used', models.CharField(help_text='Skill used in collaboration', max_length=100)),
                ('collab_type', models.CharField(choices=[('notebook', 'Notebook'), ('event', 'Event'), ('post', 'Post'), ('request', 'Request'), ('study_group', 'Study Group'), ('project', 'Project')], default='request', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Past Collaboration',
                'verbose_name_plural': 'Past Collaborations',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('skills', models.JSONField(default=list, help_text='List of user skills')),
                ('interests', models.JSONField(default=list, help_text='List of user interests')),
                ('hobbies', models.JSONField(default=list, help_text='List of user hobbies')),
                ('bio', models.TextField(blank=True, help_text='User biography')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('badges', models.JSONField(default=list, help_text='List of earned badges')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='CollabRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Collaboration request message')),
                ('skill_focus', models.CharField(help_text='Primary skill for collaboration', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_collabs', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_collabs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collaboration Request',
                'verbose_name_plural': 'Collaboration Requests',
                'ordering': ['-created_at'],
                'unique_together': {('from_user', 'to_user', 'skill_focus')},
            },
        ),
    ]
