# Generated by Django 4.2.7 on 2025-06-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_accessibility_profile_customization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='accessibility',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='customization',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='testimonials',
        ),
        migrations.AddField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
