# Generated by Django 5.1.3 on 2025-07-03 21:36

from django.db import migrations
import datetime

def set_last_daily_reset(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    today = datetime.date.today()
    for profile in Profile.objects.all():
        profile.last_daily_reset = today
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_pastcollaboration_profile_collabrequest'),
    ]

    operations = [
        migrations.RunPython(set_last_daily_reset),
    ]
