# Generated by Django 5.1.3 on 2025-07-03 22:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_daily_xp_earned_profile_last_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='xp',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
