# Generated by Django 5.1.3 on 2025-07-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_email',
            field=models.BooleanField(default=False, help_text='Show email on profile'),
        ),
    ]
