# Generated by Django 5.1.3 on 2025-07-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_show_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='show_email',
            field=models.BooleanField(default=False, help_text='Show email on profile'),
        ),
    ]
